# To start Docker in Swarm mode, you need to run `docker swarm init`
# To deploy the Grid, `docker stack deploy -c docker-compose.yml grid`
# Stop with `docker stack rm grid`
#

version: '3.7'

services:
  hub:
    image: selenium/hub:latest
    ports:
    - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
      NODE_MAX_INSTANCES: 5
      NODE_MAX_SESSION: 5
#      SCREEN_WIDTH: 1680
#      SCREEN_HEIGHT: 1050
    deploy:
      replicas: 3
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    volumes:
    - "/dev/shm:/dev/shm"
#  firefox:
#    image: selenium/node-firefox:3.141.59-copernicium
#    environment:
#      HUB_HOST: hub
#      HUB_PORT: 4444
#      NODE_MAX_INSTANCES: 5
#      NODE_MAX_SESSION: 5
#      SCREEN_WIDTH: 1680
#      SCREEN_HEIGHT: 1050
#    deploy:
#      replicas: 3
#    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'